version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=uvsproject;Username=postgres;Password=guest
    depends_on:
      - db
    ports:
      - "8000:80" 

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=uvsproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=guest
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: